services:
  odoo:
    build: .
    container_name: odoo
    depends_on:
      - db
      - otel-collector
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ../addons:/mnt/extra-addons
      - ../inDevModules:/mnt/inDevModules
    command: ["python3", "/opt/odoo/odoo-entrypoint.py"]
    networks:
      - odoo-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - odoo-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - odoo-network

networks:
  odoo-network:
    driver: bridge

volumes:
  odoo-db-data: