[options]
addons_path = /mnt/extra-addons,/mnt/tutorial-addons,/mnt/inDevModules
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$/N.bszbGOIdQyjmndO7d2w$GDKyhVQ3eID8VykTh.cSJAvHN4/./Jj2ibRTJRTfaOXUsP9PPIK43jFuZWZG0Ra9xaLL66qDHhJcZFFBNWztSg
db_host = db
db_name = odoo
db_port = 5432
db_user = odoo
db_password = odoo
limit_memory_hard = 0
limit_memory_soft = 0