[options]
log_tracing = True
otel_endpoint = http://otel-collector:4317
addons_path = /mnt/extra-addons,/mnt/tutorial-addons
admin_passwd = admin
db_host = odoo-db
db_port = 5432
db_user = Odoo_Practice
db_password = 1231

[opentelemetry]
enabled = true
endpoint = http://otel-collector:4317